---
version: '3'
volumes:
  postgres_data:
    driver: local

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "Salida:1:1,Entrada:1:1"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
      #KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT #new
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092 #new, INSIDE era PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092 #new
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE #new
      #KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  server:
    image: crimide/server
    container_name: server
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_SERVER: kafka:9092
      KEYCLOAK_CLIENTID: app_microservicios
      KEYCLOAK_REALM: 'master'
      KEYCLOAK_SECRET_KEY: 'hKCfj89bvCxg5JxCtCDlhgtSaZcuQxNT'
      KEYCLOAK_BROKER: http://localhost:8080/

  consumer:
    image: crimide/consumer
    container_name: consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_SERVER: kafka:9092
      KEYCLOAK_CLIENTID: service-app

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  key-cloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: crimide
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: start-dev
  
  
